name: Terraform Deploy

on:
  workflow_dispatch:
    inputs:
      file_path:
        description: 'Path to the variable file'
        required: true
      operation:
        description: 'to create or to destroy'
        required: true

jobs:
  deploy:
    name: Deploy Infrastructure
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -var-file=${{ github.event.inputs.variable_file_path }}

      - name: Terraform Apply
        run: terraform ${{ github.event.inputs.operation }} -var-file=${{ github.event.inputs.variable_file_path }} -auto-approve
